### PR TITLE
Adds PHP 7.2.0 compatibility fixes

### LINKED ISSUE #42: PHP Warning on 7.2
Hi, I can see it's been a while since the last update, is this plugin still supported?

Running under PHP 7.2.1 I'm getting a warning:
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /wp-content/plugins/subscribe-and-connect/classes/class-subscribe-and-connect.php on line 140

casting to array seems to fix the warning:
```
if ( 0 < count( (array) $this->settings_objs ) ) {
	foreach ( $this->settings_objs as $k => $v ) {
		$this->_settings[$k] = $v->get_settings();
	}
}
```

### PR DESCRIPTION
**Pull request by danieldudzic**
Closes #42

### CODE REVIEW

File: classes/class-subscribe-and-connect.php [hunk 1]
```diff
@@ -137,7 +137,7 @@ public function get_settings () {
 		if ( is_array( $this->_settings ) && 0 < count( $this->_settings ) ) return $this->_settings;
 
 		$this->_settings = array();
-		if ( 0 < count( $this->settings_objs ) ) {
+		if ( $this->settings_objs && 0 < count( $this->settings_objs ) ) {
```
Comment (jeffikus) [inline classes/class-subscribe-and-connect.php]: I'd also test if `$this->settings_objs` isset.

**Review by jeffikus — APPROVED** [review]
Overall seems solid - just checkout my comment on line 140 for classes/class-subscribe-and-connect.php - I'm approving pending that change.
